### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by chreman** [ContentMine/ami#45]
```
running: word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]
WS: XXXXX  .............................!!.................................................................................!!...............................!!.................................................................................................Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
    at nu.xom.ParentNode.checkCapacity(Unknown Source)
    at nu.xom.ParentNode.fastInsertChild(Unknown Source)
    at nu.xom.NonVerifyingHandler.startElement(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLNamespaceBinder.handleStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLNamespaceBinder.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
    at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at nu.xom.Builder.build(Unknown Source)
    at nu.xom.Builder.build(Unknown Source)
    at org.xmlcml.xml.XMLUtil.parseXML(XMLUtil.java:366)
    at org.xmlcml.html.HtmlFactory.parseToXHTML(HtmlFactory.java:701)
    at org.xmlcml.html.HtmlFactory.parse(HtmlFactory.java:646)
    at org.xmlcml.html.HtmlFactory.parse(HtmlFactory.java:623)
    at org.xmlcml.cmine.args.DefaultArgProcessor.getScholarlyHtmlElement(DefaultArgProcessor.java:1176)
    at org.xmlcml.cmine.files.CTree.ensureScholarlyHtmlElement(CTree.java:947)
    at org.xmlcml.cmine.args.DefaultArgProcessor.extractPSectionElements(DefaultArgProcessor.java:1159)
    at org.xmlcml.ami2.plugins.AMIArgProcessor.ensureSectionElements(AMIArgProcessor.java:191)
    at org.xmlcml.ami2.plugins.AMIArgProcessor.runRunMethodsOnChosenArgOptions(AMIArgProcessor.java:162)
    at org.xmlcml.cmine.args.DefaultArgProcessor.runAndOutput(DefaultArgProcessor.java:1100)
    at org.xmlcml.ami2.plugins.word.WordPluginOption.run(WordPluginOption.java:46)
    at org.xmlcml.ami2.plugins.CommandProcessor.runCommands(CommandProcessor.java:86)
    at org.xmlcml.ami2.plugins.CommandProcessor.processCommands(CommandProcessor.java:60)
    at org.xmlcml.ami2.plugins.CommandProcessor.main(CommandProcessor.java:176)
cmine XXXXX  3597,93s user 13,90s system 403% cpu 14:54,94 total
```

**Comment by tarrow** [comment]
As per http://stackoverflow.com/questions/1393486/error-java-lang-outofmemoryerror-gc-overhead-limit-exceeded this means that the garbage collector can't keep up with us. We can turn this off with `-XX:-UseGCOverheadLimit` but we almost certainly shouldn't. Probably means we have a memory leak somewhere.
