### ISSUE TITLE
ami2-regex ERROR org.xmlcml.cmine.args.DefaultArgProcessor

### ISSUE THREAD

**Issue by ncchung** [ContentMine/ami#59]
When running ami2-regex, I get following errors. But it does nonetheless create subdirectories for results.

`...........................................................................0    [main] ERROR org.xmlcml.cmine.args.DefaultArgProcessor  - Cannot create scholarlyHtmlElement: nu.xom.IllegalCharacterDataException: 0x2 is not allowed in XML content
19   [main] ERROR org.xmlcml.cmine.args.DefaultArgProcessor  - Cannot create scholarlyHtmlElement: nu.xom.IllegalCharacterDataException: 0x2 is not allowed in XML content
.............................................................................................Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOfRange(Arrays.java:3664)
    at java.lang.String.<init>(String.java:207)
    at java.lang.StringBuilder.toString(StringBuilder.java:407)
    at org.apache.commons.io.output.StringBuilderWriter.toString(StringBuilderWriter.java:158)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:779)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:803)
    at org.xmlcml.html.HtmlFactory.parse(HtmlFactory.java:631)
    at org.xmlcml.html.HtmlFactory.parse(HtmlFactory.java:623)
    at org.xmlcml.cmine.args.DefaultArgProcessor.getScholarlyHtmlElement(DefaultArgProcessor.java:1187)
    at org.xmlcml.cmine.files.CTree.ensureScholarlyHtmlElement(CTree.java:947)
    at org.xmlcml.cmine.args.DefaultArgProcessor.extractPSectionElements(DefaultArgProcessor.java:1170)
    at org.xmlcml.ami2.plugins.AMIArgProcessor.ensureSectionElements(AMIArgProcessor.java:250)
    at org.xmlcml.ami2.plugins.AMIArgProcessor.runRunMethodsOnChosenArgOptions(AMIArgProcessor.java:221)
    at org.xmlcml.cmine.args.DefaultArgProcessor.runAndOutput(DefaultArgProcessor.java:1111)
    at org.xmlcml.ami2.plugins.regex.RegexPlugin.main(RegexPlugin.java:35)`

**Comment by petermr** [comment]
Thanks,
It would be very helpful to know what files cause the problem. My guess is there are two independent problems:
 1 The IllegalCharacterDataException means that the XML input is corrupt. Probably not an XML file but something else. I'll try to add diganostics to locate the file.
 2 This is probably sloppy code (mine) combined with either a large number of files or a single very large file. Java has a rather small default Heap and it may be useful to increase it.  see e.g. http://opcodesolutions.com/tech/solve-java-lang-outofmemoryerror-java-heap-space/
